name: Build XCloud Desktop

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:

  build:
    name: Build XCloud Desktop
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:

      - uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: List Output Files
      #   if: success() && (matrix.os == 'windows-latest' || matrix.os == 'macos-latest')
      #   run: ls ./out/make/*/*/*/
        
      # - name: List Output Files
      #   if: success() && matrix.os == 'ubuntu-latest'
      #   run: ls ./out/make/*/*/

      # - name: Upload Artifacts
      #   if: success() && (matrix.os == 'windows-latest' || matrix.os == 'macos-latest')
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: XCloud Desktop-${{ github.sha }}
      #     path: out/make/*/*/*/

      # - name: Upload Artifacts
      #   if: success() && matrix.os == 'ubuntu-latest'
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: XCloud Desktop-${{ github.sha }}
      #     path: out/make/*/*/
